language: c
dist: xenial
cache: ccache
services:
  - docker

matrix:
  include:
    ########################################
    # ppc64le
    ########################################
    - os:   linux
      arch: ppc64le
      env:  TARGET=selftests ARCH=powerpc SUBARCH=ppc64le IMAGE=ubuntu-20.04 INSTALL=1 TARGETS=powerpc
      name: "selftests/powerpc: ppc64le"
    ########################################
    # x86_64
    ########################################
    - os:   linux
      arch: amd64
      env:  TARGET=selftests ARCH=x86 SUBARCH=x86_64 IMAGE=ubuntu-20.04 INSTALL=1 TARGETS=x86
      name: "selftests/x86: x86_64"

install:
  - docker pull linuxppc/build:$IMAGE-$(uname -m)

script:
  - mkdir -p $HOME/.ccache
  - travis_wait 50 ./arch/powerpc/tools/ci-build.sh
  - find $HOME/output
